-- 1. Create TarodCard Table
CREATE TABLE IF NOT EXISTS "TarotCards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Suit" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "UprightKeywords" text NOT NULL,
    "ReversedKeywords" text NOT NULL,
    "Meaning" text NOT NULL,
    CONSTRAINT "PK_TarotCards" PRIMARY KEY ("Id")
);

-- 2. Create ReadingSession Table
CREATE TABLE IF NOT EXISTS "ReadingSessions" (
    "Id" uuid NOT NULL,
    "UserId" text,
    "UserQuestion" text NOT NULL,
    "ReadingType" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ReadingSessions" PRIMARY KEY ("Id")
);

-- 3. Create ReadingCards Table
CREATE TABLE IF NOT EXISTS "ReadingCards" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" uuid NOT NULL,
    "CardId" integer NOT NULL,
    "Position" text NOT NULL,
    "IsReversed" boolean NOT NULL,
    CONSTRAINT "PK_ReadingCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReadingCards_ReadingSessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "ReadingSessions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReadingCards_TarotCards_CardId" FOREIGN KEY ("CardId") REFERENCES "TarotCards" ("Id") ON DELETE CASCADE
);

-- 4. Create Index (Optional but good for performance)
CREATE INDEX IF NOT EXISTS "IX_ReadingCards_CardId" ON "ReadingCards" ("CardId");
CREATE INDEX IF NOT EXISTS "IX_ReadingCards_SessionId" ON "ReadingCards" ("SessionId");
